# - name: Rust Release
#   uses: manoadamro/rust-release@v1

#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: manoadamro/rust-release@v1
#         with:
#           owner: ${{ github.repository_owner }}
#           repo: ${{ github.repository }}
#           token: ${{ secrets.GITHUB_TOKEN }}
name: Rust Release
on:
  push:
    branches: [ "master" ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manoadamro/rust-release@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

# name: Rust Release
# on:
#   push:
#     branches: [ "master" ]
# jobs:
#   release:
#     runs-on: windows-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Build
#       run: cargo build --release

#     - name: Release
#       uses: softprops/action-gh-release@v1
#       with:
#         files: |
#           target/release/hello.exe