# - name: Rust Release
#   uses: manoadamro/rust-release@v1

#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: manoadamro/rust-release@v1
#         with:
#           owner: ${{ github.repository_owner }}
#           repo: ${{ github.repository }}
#           token: ${{ secrets.GITHUB_TOKEN }}
# name: Rust Release
# on:
#   push:
#     branches: [ "master" ]
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: manoadamro/rust-release@v1
#         with:
#           owner: ${{ github.repository_owner }}
#           repo: ${{ github.repository }}
#           token: ${{ secrets.GITHUB_TOKEN }}

name: Rust Release
on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: true
        prerelease: false
        files: |
          target/release/brokendeer-playground.exe
    # - name: 创建GitHub Release
    #   id: create_release
    #   uses: actions/create-release@latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: tag的名称
    #     release_name: 发布的名字
    #     body: 发布的内容
    #     draft: false
    #     prerelease: false
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     tag_name: "v1.0.0"
    #     prerelease: true
    #     # token: ${{ secrets.GITHUB_TOKEN }}
    #     files: |
    #       target/release/brokendeer-playground.exe
        