# - name: Rust Release
#   uses: manoadamro/rust-release@v1

#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: manoadamro/rust-release@v1
#         with:
#           owner: ${{ github.repository_owner }}
#           repo: ${{ github.repository }}
#           token: ${{ secrets.GITHUB_TOKEN }}
name: Rust Release
on: [push]
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manoadamro/rust-release@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
